export const skillsData = [
  {
    category: "Programming Technologies",
    emoji: "💻",
    skills: [
      {
        name: "React",
        rating: 4.5,
        iconUrl: "/react1.png",
        animate: "animate-spin",
        desc: "Turning code into pixels and pixels into magic! ✨",
      },
      {
        name: "JavaScript",
        rating: 4.5,
        iconUrl: "/js.png",
        animate: "animate-pulse",
        desc: "Making the web dance with code, one line at a time! 💃✨",
      },
      {
        name: "TypeScript",
        rating: 4,
        iconUrl: "/ts.png",
        animate: "animate-pulse",
        desc: "Because life's too short for unpredictable code! 🚀🧩",
      },
      {
        name: "Python",
        rating: 3.5,
        iconUrl: "/py.png",
        animate: "animate-spin",
        desc: "Unraveling the mysteries of coding with the elegance of a snake 🐍🔍",
      },
      {
        name: "Node JS",
        rating: 3,
        iconUrl: "/node.png",
        animate: "animate-pulse",
        desc: "Where servers become your best friends in the digital world! 🚀",
      },
      {
        name: "Express",
        rating: 3,
        animate: "animate-pulse",
        desc: "Making server-side scripting as smooth as a Sunday morning! 🛣️🚀",
      },
      {
        name: "Angular",
        rating: 2.5,
        iconUrl: "/ag.png",
        animate: "animate-pulse",
        desc: "Keeping front-end development angular-tastic! ⚙️🅰️",
      },
    ],
  },
  {
    category: "Libraries",
    emoji: "📚",
    skills: [
      {
        name: "Recoil",
        rating: 4.5,
        iconUrl: "/recoil.jpeg",
        animate: "animate-spin",
        desc: "Making state management as easy as snapping your fingers! ✨💥",
      },
      {
        name: "Material UI",
        rating: 4.5,
        iconUrl: "/mui.png",
        animate: "animate-pulse",
        desc: "Where design meets simplicity and beauty! 🎨✨",
      },
      {
        name: "Redux",
        rating: 4,
        iconUrl: "/redux.png",
        animate: "animate-spin",
        desc: "Making state management a breeze! 🔄🚀",
      },
      {
        name: "Graph QL",
        rating: 4,
        iconUrl: "/Gql.png",
        animate: "animate-spin",
        desc: "Uniting queries and front-end like never before! 🌐✨",
      },
      {
        name: "TailWind CSS",
        rating: 4,
        iconUrl: "/Tailwind.png",
        animate: "animate-pulse",
        desc: "Spinning the web with utility-driven designs! 💻🎨",
      },
      {
        name: "Jest",
        rating: 4,
        iconUrl: "/jest.png",
        animate: "animate-spin",
        desc: "Making testing as fun as playing hide and seek with bugs! 🐞🎭",
      },
      {
        name: "RTL",
        rating: 3.5,
        iconUrl: "/rtl.png",
        animate: "animate-pulse",
        desc: "Flipping things around to make sure your UI is speaking the right language! 🔄🌍",
      },
      {
        name: "Apollo",
        rating: 3.5,
        iconUrl: "/apollo.png",
        animate: "animate-pulse",
        desc: "Building interstellar connections between your frontend and backend! 🚀🌌",
      },
      {
        name: "Tans Stack",
        rating: 3.5,
        animate: "animate-pulse",
        desc: "Making table management as easy as pie! 📊🥧",
      },
    ],
  },
  {
    category: "Scripting Language",
    emoji: "🌐",
    skills: [
      { name: "HTML5", rating: 4.5 },
      { name: "CSS", rating: 4 },
      { name: "SCSS", rating: 3.5 },
      { name: "BootStrap", rating: 3 },
    ],
  },
  {
    category: "Database",
    emoji: "🛢️",
    skills: [
      { name: "MongoDB", rating: 3.5 },
      { name: "sql", rating: 3 },
    ],
  },
  {
    category: "Tools",
    emoji: "🛠️",
    skills: [
      { name: "GitHub", rating: 4.5 },
      { name: "Aglie", rating: 4.5 },
      { name: "Firebase", rating: 3.5 },
    ],
  },
  {
    category: "Wireframing",
    emoji: "🖍️",
    skills: [
      { name: "Draw.io", rating: 4.5 },
      { name: "Microsoft PowerPoint", rating: 4.5 },
      { name: "Figma", rating: 3 },
    ],
  },
];
