export const skillsData = [
  {
    category: "Programming Technologies",
    emoji: "💻",
    skills: [
      {
        name: "React",
        rating: 4.5,
        iconUrl: "/react1.png",
        animate: "animate-spin",
        desc: "Turning code into pixels and pixels into magic! ✨",
      },
      {
        name: "JavaScript",
        rating: 4.5,
        iconUrl: "/js.png",
        animate: "animate-pulse",
        desc: "Making the web dance with code, one line at a time! 💃✨",
      },
      {
        name: "TypeScript",
        rating: 4,
        iconUrl: "/ts.png",
        animate: "animate-pulse",
        desc: "Because life's too short for unpredictable code! 🚀🧩",
      },
      {
        name: "Python",
        rating: 3.5,
        iconUrl: "/py.png",
        animate: "animate-spin",
        desc: "Unraveling the mysteries of coding with the elegance of a snake 🐍🔍",
      },
      {
        name: "Node JS",
        rating: 3,
        iconUrl: "/node.png",
        animate: "animate-pulse",
        desc: "Where servers become your best friends in the digital world! 🚀",
      },
      {
        name: "Express",
        rating: 3,
        animate: "animate-pulse",
        desc: "Making server-side scripting as smooth as a Sunday morning! 🛣️🚀",
      },
    ],
  },
  {
    category: "Libraries",
    emoji: "📚",
    skills: [
      {
        name: "Recoil",
        rating: 4.5,
        iconUrl: "/recoil.jpeg",
        animate: "animate-spin",
        desc: "Making state management as easy as snapping your fingers! ✨💥",
      },
      {
        name: "Material UI",
        rating: 4.5,
        iconUrl: "/mui.png",
        animate: "animate-pulse",
        desc: "Where design meets simplicity and beauty! 🎨✨",
      },
      {
        name: "Redux",
        rating: 4,
        iconUrl: "/redux.png",
        animate: "animate-spin",
        desc: "Making state management a breeze! 🔄🚀",
      },
      {
        name: "Graph QL",
        rating: 4,
        iconUrl: "/Gql.png",
        animate: "animate-spin",
        desc: "Uniting queries and front-end like never before! 🌐✨",
      },
      {
        name: "TailWind CSS",
        rating: 4,
        iconUrl: "/Tailwind.png",
        animate: "animate-pulse",
        desc: "Spinning the web with utility-driven designs! 💻🎨",
      },
      {
        name: "Jest",
        rating: 4,
        iconUrl: "/jest.png",
        animate: "animate-pulse",
        desc: "Making testing as fun as playing hide and seek with bugs! 🐞🎭",
      },
      {
        name: "RTL",
        rating: 3.5,
        iconUrl: "/rtl.png",
        animate: "animate-pulse",
        desc: "Flipping things around to make sure your UI is speaking the right language! 🔄🌍",
      },
      {
        name: "Apollo",
        rating: 3.5,
        iconUrl: "/apollo.png",
        animate: "animate-spin",
        desc: "Building interstellar connections between your frontend and backend! 🚀🌌",
      },
      {
        name: "Tans Stack",
        rating: 3.5,
        animate: "animate-pulse",
        desc: "Making table management as easy as pie! 📊🥧",
      },
    ],
  },
  {
    category: "Scripting Language",
    emoji: "🌐",
    skills: [
      {
        name: "HTML5",
        rating: 4.5,
        iconUrl: "/html.png",
        animate: "animate-pulse",
        desc: "The building blocks of the web 🌐✨",
      },
      {
        name: "CSS",
        rating: 4,
        iconUrl: "/css.png",
        animate: "animate-pulse",
        desc: "Making the web stylish, one element at a time! 💅🎨",
      },
      {
        name: "SCSS",
        rating: 3.5,
        iconUrl: "/sass.png",
        animate: "animate-pulse",
        desc: "Taking CSS to the next level with superpowers! 🚀🎨",
      },
      {
        name: "BootStrap",
        rating: 3,
        iconUrl: "/bootstrp.png",
        animate: "animate-pulse",
        desc: "Making web styling a breeze with ready-to-use components! 🌟👢",
      },
    ],
  },
  {
    category: "Database",
    emoji: "🛢️",
    skills: [
      {
        name: "MongoDB",
        rating: 3.5,
        iconUrl: "/mongodb.png",
        animate: "animate-pulse",
        desc: "Where data meets flexibility and scalability! 🍃🔍",
      },
    ],
  },
  {
    category: "Tools",
    emoji: "🛠️",
    skills: [
      {
        name: "GitHub",
        rating: 4.5,
        iconUrl: "/github.png",
        animate: "animate-pulse",
        desc: "Where collaboration and version control meet! 🐙👩‍💻",
      },
      {
        name: "Aglie",
        rating: 4.5,
        iconUrl: "/aglie.png",
        animate: "animate-spin",
        desc: "Let's sprint toward success together! 🏃‍♂️🚀🔍",
      },
      {
        name: "Firebase",
        rating: 3.5,
        iconUrl: "/firebase.png",
        animate: "animate-pulse",
        desc: "Lighting the way for real-time data and seamless app development! 🔥📱",
      },
    ],
  },
  {
    category: "Wireframing",
    emoji: "🖍️",
    skills: [
      {
        name: "Draw.io",
        rating: 4.5,
        iconUrl: "/draw.png",
        animate: "animate-spin",
        desc: "Drawing out ideas and solutions one diagram at a time! 🖌️📊",
      },
      {
        name: "Microsoft PowerPoint",
        rating: 4.5,
        iconUrl: "/ms.png",
        animate: "animate-pulse",
        desc: "Making presentations pop since day one! 💻🎨",
      },
      {
        name: "Figma",
        rating: 3,
        iconUrl: "/figma.png",
        animate: "animate-pulse",
        desc: "Where designs come to life collaboratively! 🎨✨",
      },
    ],
  },
];
